export default {
  ONBOARDING_GET_STARTED: "ONBOARDING_GET_STARTED",
  ONBOARDING_RECOVER: "ONBOARDING_RECOVER",
  ONBOARDING_LEARN_CONTINUE: "ONBOARDING_LEARN_CONTINUE",
  ONBOARDING_TERMS_RADIO: "ONBOARDING_TERMS_RADIO",
  ONBOARDING_PRIVACY_RADIO: "ONBOARDING_PRIVACY_RADIO",
  ONBOARDING_NAME_INPUT: "ONBOARDING_NAME_INPUT",
  ONBOARDING_PHONE_NUMBER: "ONBOARDING_PHONE_NUMBER",
  ONBOARDING_IDENTITY_NUMBER: "ONBOARDING_IDENTITY_NUMBER",
  ONBOARDING_DATE_OF_BIRTH: "ONBOARDING_DATE_OF_BIRTH",
  ONBOARDING_CREATE_IDENTITY: "ONBOARDING_CREATE_IDENTITY",
  ONBOARDING_SUCCESS_MODAL: "ONBOARDING_SUCCESS_MODAL"
};
